# ==============================
# 📘 Comparison: Euler vs Exact Solution
# ==============================

import numpy as np
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data1 = np.loadtxt('results_Y1.txt')  # Each row: X[i]    Y[i]
data2 = np.loadtxt('results_Y2.txt')  # Each row: X[i]    Y[i]

data1_last = data1[-6:]  # Last 6 points for Y1
data2_last = data2[-6:]  # Last 6 points for Y2

x_euler_1 = data1[:, 0]
y_euler_1 = data1[:, 1]
x_euler_2 = data2[:, 0]
y_euler_2 = data2[:, 1]

# --- Compute the exact analytical solution y(x) = (2/3) * x^(3/2) ---
x_exact = np.linspace(min(x_euler_1), max(x_euler_1), 200)  # 200 points for smooth curve
y_exact1 = np.exp(-x_exact) * np.sin(2*x_exact)
y_exact2 = ((2* np.exp(-x_exact) * np.cos(2*x_exact)) - (np.exp(-x_exact) * np.sin(2*x_exact)))

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# Euler method points
plt.plot(x_euler_1, y_euler_1, 'ro-', label="RK Y1", markersize=5)
plt.plot(x_euler_2, y_euler_2, 'go-', label="RK Y2", markersize=5)

# Exact solution curve
plt.plot(x_exact, y_exact1, 'b-', label="Exact Solution y1(x)", linewidth=2)
plt.plot(x_exact, y_exact2, 'm-', label="Exact Solution y2(x)", linewidth=2)

# --- Graph formatting ---
plt.title("Comparison between RK Methods for Y1, Y2 and Exact Solution", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("y(x)", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
""" plt.xlim(min(x_euler_1) - 0.5, max(x_euler_1) + 0.5)
plt.ylim(min(y_euler_1) - 0.5, max(y_exact1) + 0.5) """

# Compute axis limits centered on Euler/RK results
""" x_min = min(np.min(x_euler_1), np.min(x_euler_2))
x_max = max(np.max(x_euler_1), np.max(x_euler_2))

y_min = min(np.min(y_euler_1), np.min(y_euler_2))
y_max = max(np.max(y_euler_1), np.max(y_euler_2))

# Slight margin
plt.xlim(x_min - 0.05, x_max + 0.05)
plt.ylim(y_min - 0.05, y_max + 0.05) """

plt.margins(x=0.05, y=0.05)  # Márgenes del 5% en X y 10% en Y

""" 
If you want to graph using exact solution data1 limits, uncomment below:
plt.xlim(min(x_exact)-0.1, max(x_exact)+0.1)
plt.ylim(min(y_exact)-0.1, max(y_exact)+0.1)
"""

# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""