# ==============================
# 📘 Comparison: Convergence Method with Euler
# ==============================

import numpy as np
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data1 = np.loadtxt('error1.txt')

x_convergence1 = data1[:, 0]
y_convergence1 = data1[:, 1]

# --- Exclude the first point (index 0) ---
x_convergence1 = x_convergence1[1:]
y_convergence1 = y_convergence1[1:]

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# RK 4 method points
plt.plot(x_convergence1, y_convergence1, 'ro-', label="RK 4 Method 1", markersize=5)

# --- Graph formatting ---
plt.title("Error (Euler Method)", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("Exact error", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
# plt.xlim(min(x_convergence1) - 0.5, max(x_convergence1) + 0.5)
# plt.ylim(min(y_convergence1) - 0.5, max(y_convergence1) + 0.5)
plt.margins(x=0.05, y=0.05)  # Márgenes del 5% en X y 10% en Y

# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""