# ==============================
# 📘 Comparison: Euler vs Exact Solution
# ==============================

import numpy as np
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data = np.loadtxt('convergence_rk4.txt')  # Each row: X[i]    Y[i]

x_convergence_euler = data[:, 0]
y_convergence_euler = data[:, 1]

# --- Exclude the first point (index 0) ---
x_convergence_euler = x_convergence_euler[1:]
y_convergence_euler = y_convergence_euler[1:]

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# Euler method points
plt.plot(x_convergence_euler, y_convergence_euler, 'ro-', label="Euler Method", markersize=5)

# --- Graph formatting ---
plt.title("Convergence factor (Euler Method)", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("Convergence Factor Q[i]", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
plt.xlim(min(x_convergence_euler) - 0.5, max(x_convergence_euler) + 0.5)
plt.ylim(min(y_convergence_euler) - 0.5, max(y_convergence_euler) + 0.5)

# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""