# ==============================
# 📘 Comparison: Euler vs Exact Solution
# ==============================

import numpy as np
import math
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data1 = np.loadtxt('results_Y1.txt')  # Each row: X[i]    Y[i]
data2 = np.loadtxt('results_Y2.txt')  # Each row: X[i]    Y[i]
data3 = np.loadtxt('results_Y3.txt')  # Each row: X[i]    Y[i]

x_euler_1 = data1[:, 0]
y_euler_1 = data1[:, 1]
x_euler_2 = data2[:, 0]
y_euler_2 = data2[:, 1]
x_euler_3 = data3[:, 0]
y_euler_3 = data3[:, 1]

# --- Compute the exact analytical solution y(x) = (2/3) * x^(3/2) ---
x_exact = np.linspace(min(x_euler_1), max(x_euler_1), 200)  # 200 points for smooth curve
y_exact1 = 0.25*np.exp(-2.0*x_exact) + x_exact
y_exact2 = -0.5 * np.exp(-2.0*x_exact) + 1.0
y_exact3 = np.exp(-2.0*x_exact)
# y_exact1 = x_exact**4 + (2.0*x_exact*x_exact) - (x_exact)
# y_exact2 = (4.0*x_exact**3) + (4.0*x_exact) - 1.0
# y_exact3 = (12.0*x_exact*x_exact) + 4.0

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# RK4 method points
plt.plot(x_euler_1, y_euler_1, 'ro-', label="RK4 Method 1", markersize=5)
plt.plot(x_euler_2, y_euler_2, 'go-', label="RK4 Method 2", markersize=5)
plt.plot(x_euler_3, y_euler_3, 'mo-', label="RK4 Method 3", markersize=5)

# Exact solution curve
plt.plot(x_exact, y_exact1, 'b-', label="Exact Solution y1(x)", linewidth=2)
plt.plot(x_exact, y_exact2, 'c-', label="Exact Solution y2(x)", linewidth=2)
plt.plot(x_exact, y_exact3, 'y-', label="Exact Solution y3(x)", linewidth=2)

# --- Graph formatting ---
plt.title("Comparison between Runge-Kutta 4 for Y1, Y2, Y3 and Exact Solution", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("y(x)", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
""" plt.xlim(min(x_euler_1) - 0.5, max(x_euler_1) + 5.0)
plt.ylim(min(y_euler_1) - 0.5, max(y_exact1) + 20.0) """

# If you want to graph using exact solution data1 limits, uncomment below:
plt.xlim(min(x_exact)-0.1, max(x_exact)+2.0)
plt.ylim(min(y_exact1)-1.0, max(y_exact1)+3.0)


# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""