# ==============================
# 📘 Comparison: Euler vs Exact Solution
# ==============================

import numpy as np
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data1 = np.loadtxt('euler_Y1.txt')  # Each row: X[i]    Y[i]
data2 = np.loadtxt('euler_Y2.txt')  # Each row: X[i]    Y[i]
data3 = np.loadtxt('runge_kutta_Y1.txt')  # Each row: X[i]    Y[i]
data4 = np.loadtxt('runge_kutta_Y2.txt')  # Each row: X[i]    Y[i]


x_euler_1 = data1[:, 0]
y_euler_1 = data1[:, 1]
y_euler_2 = data2[:, 1]
x_runge_kutta_1 = data3[:, 0]
y_runge_kutta_1 = data3[:, 1]
y_runge_kutta_2 = data4[:, 1]

""" # --- Compute the exact analytical solution y(x) = (2/3) * x^(3/2) ---
x_exact = np.linspace(min(x_euler_1), max(x_euler_1), 200)  # 200 points for smooth curve
y_exact1 = 2*x_exact*np.sin(x_exact)
y_exact2 = 2*(np.sin(x_exact) + (x_exact*np.cos(x_exact))) """

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# Euler
plt.plot(x_euler_1, y_euler_1, 'ro-', label="Euler Y1", markersize=5)
plt.plot(x_euler_1, y_euler_2, 'bo-', label="Euler Y2", markersize=5)

# Runge–Kutta 4
plt.plot(x_runge_kutta_1, y_runge_kutta_1, 'go-', label="RK4 Y1", markersize=5)
plt.plot(x_runge_kutta_1, y_runge_kutta_2, 'mo-', label="RK4 Y2", markersize=5)

# Exact solution curve
""" plt.plot(x_exact, y_exact1, 'b-', label="Exact Solution y1(x)", linewidth=2)
plt.plot(x_exact, y_exact2, 'm-', label="Exact Solution y2(x)", linewidth=2) """

# --- Graph formatting ---
plt.title("Comparison between Euler's Method's for Y1, Y2 and Runge Kutta Method for Y1, Y2", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("y(x)", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
# plt.xlim(min(x_euler_1) - 0.5, max(x_euler_1) + 0.5)
# plt.ylim(min(y_euler_1) - 0.5, max(y_exact1) + 0.5)

plt.margins(x=0.05, y=0.05)  # Márgenes del 5% en X y 10% en Y

""" 
If you want to graph using exact solution data1 limits, uncomment below:
plt.xlim(min(x_exact)-0.1, max(x_exact)+0.1)
plt.ylim(min(y_exact)-0.1, max(y_exact)+0.1)
"""

# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""