# ==============================
# 📘 Comparison: Euler vs Exact Solution
# ==============================

import numpy as np
import matplotlib.pyplot as plt

# --- Read data from results.txt (generated by C code) ---
data = np.loadtxt('results.txt')  # Each row: X[i]    Y[i]

x_rk4 = data[:, 0]
y_rk4 = data[:, 1]

# --- Compute the exact analytical solution y(x) = (2/3) * x^(3/2) ---
x_exact = np.linspace(min(x_rk4), max(x_rk4), 200)  # 200 points for smooth curve
y_exact = 1.0 / (x_exact * x_exact + 1.0)

# --- Plot both curves ---
plt.figure(figsize=(8, 6))

# Runge Kutta of order 4 method points
plt.plot(x_rk4, y_rk4, 'ro-', label="R.K. 4 Method", markersize=5)

# Exact solution curve
plt.plot(x_exact, y_exact, 'b-', label="Exact Solution", linewidth=2)

# --- Graph formatting ---
plt.title("Comparison between Runge Kutta of order 4 method and Exact Solution", fontsize=13)
plt.xlabel("x", fontsize=12)
plt.ylabel("y(x)", fontsize=12)
plt.legend()
plt.grid(True)

# Axis limits slightly extended
""" plt.xlim(min(x_rk4) - 100.0, max(x_rk4) + 100.0)
plt.ylim(min(y_rk4) - 10.0, max(y_rk4) + 100.0) """

plt.xlim(min(x_exact)-5.0, max(x_exact)+0.1)
plt.ylim(min(y_exact)-20.0, max(y_exact)+5.0)


# Show plot
plt.show()

"""
https://matplotlib.org/stable/api/markers_api.html ---> Different types of points
https://matplotlib.org/stable/gallery/color/named_colors.html ----> Colors
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle --> Line styles
"""